Python DSOs: link DSO against -lgcc
Fixes importing these into Python, e.g.:

In [1]: import volumedriver.storagerouter.storagerouterclient as src
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-880e9800c14d> in <module>()
----> 1 import volumedriver.storagerouter.storagerouterclient as src

ImportError: [...]/storagerouterclient.so: undefined symbol: __cpu_model

Conflicts:
	src/filesystem/c-api/Makefile.am